version: '2'
checks:
  file-lines:
    config:
      threshold: 1000
  method-lines:
    config:
      threshold: 70
  return-statements:
    config:
      threshold: 20
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
  - 'dist/'
