// Generated by CoffeeScript 1.3.1
(function() {
  var $;

  $ = jQuery;

  $.extend(true, $.hlf, {
    hoverIntent: {
      debug: false,
      sensitivity: 8,
      interval: 300,
      toString: function(context) {
        switch (context) {
          case 'data':
            return 'hlfHoverIntent';
          case 'log':
            return 'hover-intent:';
          default:
            return 'hlf.HoverIntent';
        }
      }
    },
    mouse: {
      x: {
        current: 0,
        previous: 0
      },
      y: {
        current: 0,
        previous: 0
      }
    }
  });

  (function(ns, m) {
    var check, clear, dat, log, nsDat, nsLog, track;
    nsDat = ns.toString('data');
    nsLog = ns.toString('log');
    dat = function(name) {
      return "" + nsDat + name;
    };
    log = ns.debug === true ? $.hlf.log : $.noop;
    check = function(evt) {
      var $t, intentional, interval, sensitivity, timer, trigger;
      trigger = function(evtType) {
        $t.trigger("true" + evtType);
        return log(nsLog, "true" + evtType);
      };
      $t = $(this);
      intentional = $t.data(dat()) || true;
      timer = $t.data(dat('Timer')) || null;
      sensitivity = $t.data(dat('Sensitivity')) || ns.sensitivity;
      interval = $t.data(dat('Interval')) || ns.interval;
      return $t.data(dat('Timer'), setTimeout(function() {
        var type;
        intentional = Math.abs(m.x.previous - m.x.current) + Math.abs(m.y.previous - m.y.current) > sensitivity;
        intentional = intentional;
        m.x.previous = evt.pageX;
        m.y.previous = evt.pageY;
        $t.data(dat(), intentional);
        if (intentional === true) {
          switch (evt.type) {
            case 'mouseout':
              type = 'mouseleave';
              if (!$t.data('hlfIsActive')) {
                clear($t);
              }
              break;
            case 'mouseover':
              type = 'mouseenter';
          }
          return trigger(type);
        }
      }, interval));
    };
    track = function(evt) {
      m.x.current = evt.pageX;
      return m.y.current = evt.pageY;
    };
    clear = function($t) {
      clearTimeout($t.data(dat('Timer')));
      $t.removeData(dat('Timer'));
      return $t.removeData(dat());
    };
    $.event.special.truemouseenter = {
      setup: function(data, namespaces) {
        return $(this).on({
          mouseenter: check,
          mousemove: track
        });
      },
      teardown: function(data, namespaces) {
        return $(this).off({
          mouseenter: check,
          mousemove: track
        });
      }
    };
    return $.event.special.truemouseleave = {
      setup: function(data, namespaces) {
        return $(this).on({
          mouseleave: check
        });
      },
      teardown: function(data, namespaces) {
        return $(this).off({
          mouseleave: check
        });
      }
    };
  })($.hlf.hoverIntent, $.hlf.mouse);

}).call(this);
